export const mockProfiles = [
    {
      id: '1',
      name: 'John Doe',
      email: 'john@example.com',
      phone: '123-456-7890',
      address: '1600 Amphitheatre Parkway, Mountain View, CA',
      description: 'Software Engineer with 5 years of experience in web development',
      photo: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    {
      id: '2',
      name: 'Jane Smith',
      email: 'jane@example.com',
      phone: '234-567-8901',
      address: '1 Infinite Loop, Cupertino, CA',
      description: 'Product Manager with expertise in agile methodologies',
      photo: 'https://randomuser.me/api/portraits/women/1.jpg',
    },
    {
      id: '3',
      name: 'Robert Johnson',
      email: 'robert@example.com',
      phone: '345-678-9012',
      address: '350 5th Ave, New York, NY',
      description: 'UX Designer passionate about creating intuitive user interfaces',
      photo: 'https://randomuser.me/api/portraits/men/2.jpg',
    },
    {
      id: '4',
      name: 'Emily Davis',
      email: 'emily@example.com',
      phone: '456-789-0123',
      address: '1 Hacker Way, Menlo Park, CA',
      description: 'Data Scientist specializing in machine learning algorithms',
      photo: 'https://randomuser.me/api/portraits/women/2.jpg',
    },
    {
      id: '5',
      name: 'Michael Wilson',
      email: 'michael@example.com',
      phone: '567-890-1234',
      address: '701 1st Ave, Sunnyvale, CA',
      description: 'DevOps Engineer with cloud infrastructure expertise',
      photo: 'https://randomuser.me/api/portraits/men/3.jpg',
    },
  ];